[default]
[default.settings]
[default.settings.db]
username = "postgres"
password = "1234"
host = "127.0.0.1"
port = 5432
db_name = "gis_files"



[docker]
[docker.settings]
[docker.settings.db]
host = "db"
port = 5432
